### ISSUE TITLE
Exceptions in Molecules::connect are inconsistent

### ISSUE THREAD

**Issue by hrabbel** [LeMonADE-project/LeMonADE#1]
In Molecules::connect(a,b) in  Molecules.h:
-line 491 catches std::out_of_range
-line 504 throws std::range_error
-line 507 catches std::string
-line 511 throws std::runtime_error
The functions in the preceeding try-block throw only std::runtime_error (They are defined in ConnectedDecorator.h)

**Comment by Bondoki** [comment]
I will take care of this issue in the next commit.
