### ISSUE TITLE
Protect master branch?

### ISSUE THREAD

**Issue by MartinWenge** [LeMonADE-project/LeMonADE#10]
Protecting the master branch would force us to create a pull request for every merge and disables a forced merge. If we protect this branch we can modify the settings defining what is necessary to accept a pull request.

**Comment by hrabbel** [comment]
Should definitely be done to my opinion. The master branch should be guaranteed to be as stable as possible, thus review by others before merging into it makes perfect sense.

**Comment by MartinWenge** [comment]
Master branch is protected now. Should we add status checks (https://developer.github.com/v3/repos/statuses/) to control every commit? Or is this too much effort?

**Comment by hrabbel** [comment]
Not sure. Of  course it can be useful, but I feel like it might be too much effort. Other opinions?

**Comment by Bondoki** [comment]
I agree and we already protect the master branch. We can close this issue.
