### ISSUE TITLE
Dangerous missing of copy constructor in FastBondset/SlowBondest

### ISSUE THREAD

**Issue by Bondoki** [LeMonADE-project/LeMonADE#14]
There's a dangerous bug in FastBondset/SlowBondset. Both classes provide the copy constructor interface BondsetType(const BondsetType& rhs){} with an emtpy method. This can lead to unwanted behavior if we reference this object e.g.

``` sh
    Ing myIngredients;
    ...load file or myIngredients.modifyBondset().addBFMclassicBondset()
    myIngredients.getBondset().size(); // that's ok - size 108 in scBFM and 50 in bccBFM
    const FastBondset bondsetType = myIngredients.getBondset();
    bondsetType.size(); // that's buggy - no error and size=0
```

ToDo: either delete the interface of the copy constructor or provide the copy constructor. The latter should be done (+ tests).

**Comment by MartinWenge** [comment]
solved by #19
