### ISSUE TITLE
Cleanup of NumericFunctions.h

### ISSUE THREAD

**Issue by hrabbel** [LeMonADE-project/LeMonADE#2]
- Are the functions useful? For example, the radius of gyration functions seem to be used only in class AnalyzerRadiusOfGyration. 
  -Suggestion: They could be implemented directly there, in AnalyzerRadiusOfGyration.h, to reduce layers and improve readability. Or, the stuff within NumericFunctions.h could go into a namespace to make it clear where the function is coming from, when it is used.

**Comment by Bondoki** [comment]
delete NumericFunctions.h? Who is using it? This header provides only very, very basic calculation everbody can implement  an analyzer by himself. I would prefer to delete this one and provide an AnalyzerRg or AnalyzerCOM for evaluation. Or did I misunderstand the question?

**Comment by hrabbel** [comment]
Suggestions are:
-delete NumericFunctions.h
-delete NumericTools.h
-check for standard tools in C++11, e.g. histogram classes, otherwise provide useful histogram

**Comment by MartinWenge** [comment]
Numeric Tools are used by the AnalyzerRadiusOfGyration, only, so we should change this before deleting the headers. 

The histogram class seems to be useful, but not complete. We should think about public members we need to implement to make is more useful. For example:

arbitrary dimensions by using the map with tuples using variadic template argument (c++11):
`std::map< std::tuple < typename... TupleType > ,double> histogram;`

operators +,-,+=,-=, <<

statistics like min, max, meanValue, minimalBin, maximalBin, ...

**Comment by klemens-morgenstern** [comment]
Just FYI: there is a proposal for a histogram library for boost: https://github.com/HDembinski/histogram
Not ready for boost yet and a bit heavy on the preprocessor usage, since it's for C++98, but elsewise it seems rather solid.

**Comment by hrabbel** [comment]
Looks interesting - thanks for the suggestion.

**Comment by MartinWenge** [comment]
this issue is fixed by commit #49970e5 in pull request #38
