### ISSUE TITLE
MoveAddBccMonomer

### ISSUE THREAD

**Issue by hrabbel** [LeMonADE-project/LeMonADE#39]
I think this move is not necessary any more. Can we remove it from the project? As far as I remember it was used initially, because a general excluded volume feature for both sc and bcc BFM existed. That feature had to distinguish between sc and bcc. Now we have separate features for those two, which means they automatically distinguish between sc and bcc by construction, so to speak.

**Comment by MartinWenge** [comment]
This move is provided to enable the bcc bfm in the project. If someone needs to create a bcc bfm conformation he can use this move. I will consider a test for this somehow in #47

**Comment by Bondoki** [comment]
close by pull request #47
