### ISSUE TITLE
Add FeatureWall as standard

### ISSUE THREAD

**Issue by Bondoki** [LeMonADE-project/LeMonADE#45]
There's the need for some simulations to constrain the space for the monomers not directly by adjusting the simulation box. Instead we should provide a feature FeatureWall handling the constraint movement in space aka as (hard) wall. Applications running for simulating osmosis, particle bath, deformations, fixed pressure ensemble etc. will benefit. My suggestion for the file command is related to the Hesse normal form in the simplest case along the lattice axis for the normal vector **n** i.e. **n** = **ex, ey** or **ez** with an arbitrary point **a** on the wall. I think the simplest case is sufficient due to discretization of the lattice diagonal walls are harder to implement.
- file command:

> # !wall normal point

For example:

> # !wall z 0

The latter one should be implemented (under periodic boundary conditions) in the same behavior as we would have non-periodic boundary conditions to match the same physics.

**Comment by MartinWenge** [comment]
fixed by #59
