### ISSUE TITLE
Delete Interface init, check, and apply in MoveBase

### ISSUE THREAD

**Issue by Bondoki** [LeMonADE-project/LeMonADE#49]
Due to the inheritance of all specialized moves out of MoveBase their corresponding implementation init(), check(), and apply() in MoveBase are hidden and never called. There's also no need to provide this interface. For readability and understanding we can delete them as already mentioned in the todo list.

**Comment by MartinWenge** [comment]
I would suggest to extend the crtp to the base move to make sure all moves inheriting from Move base provide the init, check and apply function using crtp.

**Comment by Bondoki** [comment]
Let's try :) But I think there's a problem that we need a non-CRTP parent class in `Feature.h` for providing a general interface for call of all (possible) moves. But I'm not sure about this. This stuff in `Feature.h` is not directly related to init, check and apply in BaseMove, because they are hidden by the specialization anyway.

**Comment by MartinWenge** [comment]
solved by #68
