### ISSUE TITLE
remove IngredientsUpdater and use AbstractUpdater

### ISSUE THREAD

**Issue by MartinWenge** [LeMonADE-project/LeMonADE#55]
There are some todo tags in the files

> include/LeMonADE/updater/UpdaterSimpleSimulator.h:48: \* @todo remove IngredientsUpdater and use AbstractUpdater
> include/LeMonADE/updater/UpdaterSimpleSimulator.h:54:class UpdaterSimpleSimulator:public IngredientsUpdater<IngredientsType>
> include/LeMonADE/updater/UpdaterSimpleSimulator.h:65:  :IngredientsUpdater<IngredientsType>(ing),nsteps(steps)
> include/LeMonADE/updater/UpdaterSynchronize.h:44:template< class T > class UpdaterSynchronize: public IngredientsUpdater < T >
> include/LeMonADE/updater/UpdaterSynchronize.h:47:       UpdaterSynchronize( T& val):IngredientsUpdater< T >(val){};
> include/LeMonADE/updater/AbstractUpdater.h:82: \* @class IngredientsUpdater
> include/LeMonADE/updater/AbstractUpdater.h:88: \* @todo remove IngredientsUpdater from the LeMonADe-project
> include/LeMonADE/updater/AbstractUpdater.h:90:template < class IngredientsType > class IngredientsUpdater: public AbstractUpdater
> include/LeMonADE/updater/AbstractUpdater.h:97:  IngredientsUpdater(IngredientsType& val):ingredients(val){}
> include/LeMonADE/updater/AbstractUpdater.h:98:  virtual ~IngredientsUpdater(){}

telling us where to remove the IngredientsUpdater class, which seems to be quite useless. Lets remove it for version 2.0.

**Comment by hrabbel** [comment]
Yes, good point. It's an unnecessary extra layer.

**Comment by hrabbel** [comment]
resolved by merging pull request #63
