### ISSUE TITLE
Add standard updaters for system setup

### ISSUE THREAD

**Issue by hrabbel** [LeMonADE-project/LeMonADE#6]
Single chain (SAW,RW), melt, bilayer, explicit solvent, are all frequent use cases. We could provide updaters for at least some of such standard systems. Anyone have an implementation? I have one which I could provide, but it should be discussed first.

**Comment by Bondoki** [comment]
Good idea. One of the fundamental tasks is the generating of structures. I can provide a simple updater for creating melt of linear chains in the vicinity of objects or none in ScBFM or BccBFM.

**Comment by hrabbel** [comment]
After discussing this we have agreed to provide two updaters: One for melt of linear chains, and one for adding explicit solvent.

**Comment by MartinWenge** [comment]
Maybe it is a bit too general, but the UpdaterSetupLinearChains #60  can do the job of creating random walks, self avoiding walks, polymer melts and of course also add explicit solvent as chains of length 1. To make this clear we could write an executable using all these things and add it for instance to the examples. Maybe in version 2.1.0 ;o)

**Comment by Bondoki** [comment]
fixed by #60
