### ISSUE TITLE
Better syntax for Ingredients::synchronize(...)

### ISSUE THREAD

**Issue by hrabbel** [LeMonADE-project/LeMonADE#7]
The currently used syntax in not very intuitive. We could provide a convenience function in Ingredients, which allows to change the syntax from

/********_begin pseudo code**_******_/
ingredients.synchronize(ingredients);
/**_*****_end pseudo code**_*******/

to

/********_begin pseudo code**_******_/
ingredients.synchronize();
/**_*****_end pseudo code**_*******/

**Comment by Bondoki** [comment]
I agree, we should write a convience function in ingredients. But maybe there is a problem of inheritence of synchronize because this function is provided as public function in feature.h. Is it possible to restrict the access to protected?
