### ISSUE TITLE
Should the header Lemonade.h be removed?

### ISSUE THREAD

**Issue by hrabbel** [LeMonADE-project/LeMonADE#9]
I have found it to be not too convenient for a few reasons:
- One forgets to keep it updated, so it tends to be cluttered with things that are not used, while some useful headers are not included
- It can lead to longer compilation times, when a change is made in some header included through Lemonade.h. This is especially annoying if classes defined in this header were not even used

**Comment by Bondoki** [comment]
Yes, you're right. Also for my opinion we can remove the LeMonADE.h. Maybe we should also merge Version.h into Ingredients.h? Where is a good place to store the Version number and the abbreviation of LeMonADE?
