### ISSUE TITLE
This Pointer in Vector3D

### ISSUE THREAD

**Issue by Bondoki** [LeMonADE-project/LeMonADE#95]
maybe there's an implementation issue in Vector3D due to discard qualifier issue.
Change
`//! Returns the Vector3D itself
	Vector3D& getVector3D()
	{
		  return *this;
	}`
to
`//! Returns the Vector3D itself
	const Vector3D& getVector3D() const
	{
		  return *this;
	}`

and introduce 
`//! Returns the Vector3D itself
	Vector3D& modifyVector3D() 
	{
		  return *this;
	}`

Write test for Vector3D as style as
`vec2A.getVector3D().getX();`
`vec2A.modifyVector3D().setX(34);`

**Comment by MartinWenge** [comment]
closed by #90
